packages:
  - elections-tracker
  - website
  - book-arena
catalog:
  "@astrojs/ts-plugin": ^1.10.4
  "@chromatic-com/storybook": ^3
  "@eslint/compat": ^1.2.5
  "@eslint/js": ^9.18.0
  "@hono/node-server": ^1.14.0
  "@storybook/addon-essentials": ^8.6.12
  "@storybook/addon-svelte-csf": ^5.0.0-next.0
  "@storybook/blocks": ^8.6.12
  "@storybook/experimental-addon-test": ^8.6.12
  "@storybook/svelte": ^8.6.12
  "@storybook/sveltekit": ^8.6.12
  "@storybook/test": ^8.6.12
  "@sveltejs/adapter-node": ^5.2.11
  "@sveltejs/kit": ^2.16.0
  "@sveltejs/vite-plugin-svelte": ^5.0.0
  "@tailwindcss/forms": ^0.5.9
  "@tailwindcss/typography": ^0.5.15
  "@tailwindcss/vite": ^4.0.0
  "@testing-library/jest-dom": ^6.6.3
  "@testing-library/svelte": ^5.2.4
  "@types/node": ^22.13.17
  "@typescript-eslint/parser": ^8.29.0
  "@vitest/browser": 3.1.1
  "@vitest/coverage-v8": 3.1.1
  astro: ^5.5.6
  daisyui: ^5.0.11
  drizzle-kit: ^0.30.2
  drizzle-orm: ^0.40.0
  eslint: ^9.18.0
  eslint-config-prettier: ^10.0.1
  eslint-plugin-astro: ^1.3.1
  eslint-plugin-svelte: ^3.0.0
  globals: ^16.0.0
  hono: ^4.7.5
  jsdom: ^26.0.0
  playwright: ^1.51.1
  postgres: ^3.4.5
  prettier: ^3.4.2
  prettier-plugin-svelte: ^3.3.3
  prettier-plugin-tailwindcss: ^0.6.11
  sharp: ^0.33.5
  storybook: ^9.0.4
  svelte: ^5.0.0
  svelte-check: ^4.0.0
  tailwindcss: ^4.0.0
  typescript: ^5.0.0
  typescript-eslint: ^8.20.0
  vite: ^6.0.0
  vitest: ^3.0.0
